import {
  User,
  Shield,
  HelpCircle,
  MessageSquare,
  Send,
  Bug,
  FileText,
  Lock,
  Info,
  LogOut,
  Globe,
  GraduationCap,
  BookOpen,
  Mail,
  Laptop,
  Briefcase,
} from 'lucide-react-native';
import type { SettingSection, ExternalService } from '@/types/settings.types';

export const settingSections: SettingSection[] = [
  {
    id: 'account',
    title: 'Account',
    items: [
      {
        id: 'profile-account',
        label: 'Profile & Account',
        icon: User,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/profile-account',
      },
    ],
  },
  {
    id: 'privacy-security',
    title: 'Privacy & Security',
    items: [
      {
        id: 'privacy-data',
        label: 'Privacy & Data',
        icon: Shield,
        iconBgClass: 'bg-success',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/privacy-data',
      },
    ],
  },
  {
    id: 'support',
    title: 'Support',
    items: [
      {
        id: 'help-center',
        label: 'Help Center',
        icon: HelpCircle,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/help-center',
      },
      // {
      //   id: 'contact-rep',
      //   label: 'Contact Student Rep',
      //   icon: MessageSquare,
      //   iconBgClass: 'bg-success',
      //   iconColor: '#fff',
      //   type: 'external',
      //   externalUrl: 'https://ktusrc.com/contact',
      // },
      {
        id: 'send-feedback',
        label: 'Send Feedback',
        icon: Send,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/feedback',
      },
      // {
      //   id: 'report-bug',
      //   label: 'Report a Bug',
      //   icon: Bug,
      //   iconBgClass: 'bg-danger',
      //   iconColor: '#fff',
      //   type: 'external',
      //   externalUrl: 'https://ktusrc.com/bug-report',
      // },
    ],
  },
  {
    id: 'legal',
    title: 'Legal',
    items: [
      {
        id: 'terms',
        label: 'Terms of Service',
        icon: FileText,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'external',
        externalUrl: 'https://ktusrc.com/terms',
      },
      {
        id: 'privacy-policy',
        label: 'Privacy Policy',
        icon: Lock,
        iconBgClass: 'bg-success',
        iconColor: '#fff',
        type: 'external',
        externalUrl: 'https://ktusrc.com/privacy',
      },
      {
        id: 'about',
        label: 'About',
        icon: Info,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/about',
      },
    ],
  },
  {
    id: 'signout',
    items: [
      {
        id: 'sign-out',
        label: 'Sign Out',
        icon: LogOut,
        iconBgClass: 'bg-danger',
        iconColor: '#fff',
        type: 'action',
        action: 'signout',
        isDestructive: true,
      },
    ],
  },
];

export const externalServices: ExternalService[] = [
  {
    id: 'school-website',
    name: 'School Website',
    url: 'https://www.ktu.edu.gh',
    icon: Globe,
    iconBgClass: 'bg-accent',
    iconColor: '#fff',
  },
  {
    id: 'student-portal',
    name: 'Student Portal',
    url: 'https://apps.ktu.edu.gh',
    icon: GraduationCap,
    iconBgClass: 'bg-success',
    iconColor: '#fff',
  },
  {
    id: 'library',
    name: 'Library',
    url: 'https://library.ktu.edu.gh',
    icon: BookOpen,
    iconBgClass: 'bg-accent',
    iconColor: '#fff',
  },
  {
    id: 'webmail',
    name: 'Webmail',
    url: 'https://mail.ktu.edu.gh',
    icon: Mail,
    iconBgClass: 'bg-danger',
    iconColor: '#fff',
  },
  {
    id: 'learning-portal',
    name: 'Learning Portal',
    url: 'https://elearning.ktu.edu.gh',
    icon: Laptop,
    iconBgClass: 'bg-success',
    iconColor: '#fff',
  },
  {
    id: 'career-services',
    name: 'Career Services',
    url: 'https://careers.ktu.edu.gh',
    icon: Briefcase,
    iconBgClass: 'bg-accent',
    iconColor: '#fff',
  },
];
