import {
  User,
  HelpCircle,
  Send,
  FileText,
  Lock,
  Info,
  LogOut,
  Globe,
  GraduationCap,
  BookOpen,
  Laptop,
} from 'lucide-react-native';
import type { SettingSection, ExternalService } from '@/types/settings.types';

export const settingSections: SettingSection[] = [
  {
    id: 'account',
    title: 'Account',
    items: [
      {
        id: 'profile-account',
        label: 'Profile & Account',
        icon: User,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/profile-account',
      },
    ],
  },
  {
    id: 'support',
    title: 'Support',
    items: [
      {
        id: 'help-center',
        label: 'Help Center',
        icon: HelpCircle,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/help-center',
      },
      {
        id: 'send-feedback',
        label: 'Send Feedback',
        icon: Send,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/feedback',
      },
    ],
  },
  {
    id: 'legal',
    title: 'Legal',
    items: [
      {
        id: 'terms',
        label: 'Terms of Service',
        icon: FileText,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/terms-of-service',
      },
      {
        id: 'privacy-policy',
        label: 'Privacy Policy',
        icon: Lock,
        iconBgClass: 'bg-success',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/privacy-policy',
      },
      {
        id: 'about',
        label: 'About',
        icon: Info,
        iconBgClass: 'bg-accent',
        iconColor: '#fff',
        type: 'navigate',
        route: '/settings/about',
      },
    ],
  },
  {
    id: 'signout',
    items: [
      {
        id: 'sign-out',
        label: 'Sign Out',
        icon: LogOut,
        iconBgClass: 'bg-danger',
        iconColor: '#fff',
        type: 'action',
        action: 'signout',
        isDestructive: true,
      },
    ],
  },
];

export const externalServices: ExternalService[] = [
  {
    id: 'school-website',
    name: 'School Website',
    url: 'https://ktu.edu.gh',
    icon: Globe,
    iconBgClass: 'bg-accent',
    iconColor: '#fff',
  },
  {
    id: 'student-portal',
    name: 'Student Portal',
    url: 'https://connect.ktu.edu.gh/',
    icon: GraduationCap,
    iconBgClass: 'bg-success',
    iconColor: '#fff',
  },
  {
    id: 'library',
    name: 'Library',
    url: 'https://ktu.edu.gh/the-university/directorates-centres/the-university-library/',
    icon: BookOpen,
    iconBgClass: 'bg-accent',
    iconColor: '#fff',
  },
  // {
  //   id: 'webmail',
  //   name: 'Webmail',
  //   url: 'https://mail.ktu.edu.gh',
  //   icon: Mail,
  //   iconBgClass: 'bg-danger',
  //   iconColor: '#fff',
  // },
  {
    id: 'VLE',
    name: 'VLE',
    url: 'https://vle.ktu.edu.gh/login/index.php',
    icon: Laptop,
    iconBgClass: 'bg-success',
    iconColor: '#fff',
  },
  // {
  //   id: 'career-services',
  //   name: 'Career Services',
  //   url: 'https://careers.ktu.edu.gh',
  //   icon: Briefcase,
  //   iconBgClass: 'bg-accent',
  //   iconColor: '#fff',
  // },
];
