
  create table "public"."departments" (
    "id" uuid not null default gen_random_uuid(),
    "faculty_id" uuid not null,
    "name" text not null,
    "logo_uri" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."departments" enable row level security;


  create table "public"."faculties" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "logo_uri" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."faculties" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "username" text,
    "full_name" text,
    "email" text,
    "index_number" text,
    "faculty_id" uuid,
    "department_id" uuid,
    "level" smallint,
    "phone" text,
    "avatar_url" text,
    "bio" text,
    "completed" boolean not null default false,
    "onboarding_completed_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "program_id" bigint
      );


alter table "public"."profiles" enable row level security;


  create table "public"."programs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "department" uuid not null
      );


alter table "public"."programs" enable row level security;

CREATE UNIQUE INDEX departments_faculty_name_unique ON public.departments USING btree (faculty_id, name);

CREATE UNIQUE INDEX departments_name_key ON public.departments USING btree (name);

CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id);

CREATE UNIQUE INDEX faculties_name_key ON public.faculties USING btree (name);

CREATE UNIQUE INDEX faculties_pkey ON public.faculties USING btree (id);

CREATE INDEX idx_departments_faculty_id ON public.departments USING btree (faculty_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX programs_pkey ON public.programs USING btree (id);

alter table "public"."departments" add constraint "departments_pkey" PRIMARY KEY using index "departments_pkey";

alter table "public"."faculties" add constraint "faculties_pkey" PRIMARY KEY using index "faculties_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."programs" add constraint "programs_pkey" PRIMARY KEY using index "programs_pkey";

alter table "public"."departments" add constraint "departments_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculties(id) ON DELETE CASCADE not valid;

alter table "public"."departments" validate constraint "departments_faculty_id_fkey";

alter table "public"."departments" add constraint "departments_faculty_name_unique" UNIQUE using index "departments_faculty_name_unique";

alter table "public"."departments" add constraint "departments_name_key" UNIQUE using index "departments_name_key";

alter table "public"."faculties" add constraint "faculties_name_key" UNIQUE using index "faculties_name_key";

alter table "public"."profiles" add constraint "profiles_auth_user_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_auth_user_fkey";

alter table "public"."profiles" add constraint "profiles_department_id_fkey" FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_department_id_fkey";

alter table "public"."profiles" add constraint "profiles_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculties(id) ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_faculty_id_fkey";

alter table "public"."profiles" add constraint "profiles_program_id_fkey" FOREIGN KEY (program_id) REFERENCES public.programs(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."profiles" validate constraint "profiles_program_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."programs" add constraint "programs_department_fkey" FOREIGN KEY (department) REFERENCES public.departments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."programs" validate constraint "programs_department_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  -- Insert a minimal profile row with default/null values
  insert into public.profiles (
    id,
    email,
    created_at,
    updated_at,
    completed
  )
  values (
    new.id,
    new.email,
    now(),
    now(),
    false     -- onboarding not completed by default
  )
  on conflict (id) do nothing; -- idempotent

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_timestamp_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."departments" to "anon";

grant insert on table "public"."departments" to "anon";

grant references on table "public"."departments" to "anon";

grant select on table "public"."departments" to "anon";

grant trigger on table "public"."departments" to "anon";

grant truncate on table "public"."departments" to "anon";

grant update on table "public"."departments" to "anon";

grant delete on table "public"."departments" to "authenticated";

grant insert on table "public"."departments" to "authenticated";

grant references on table "public"."departments" to "authenticated";

grant select on table "public"."departments" to "authenticated";

grant trigger on table "public"."departments" to "authenticated";

grant truncate on table "public"."departments" to "authenticated";

grant update on table "public"."departments" to "authenticated";

grant delete on table "public"."departments" to "postgres";

grant insert on table "public"."departments" to "postgres";

grant references on table "public"."departments" to "postgres";

grant select on table "public"."departments" to "postgres";

grant trigger on table "public"."departments" to "postgres";

grant truncate on table "public"."departments" to "postgres";

grant update on table "public"."departments" to "postgres";

grant delete on table "public"."departments" to "service_role";

grant insert on table "public"."departments" to "service_role";

grant references on table "public"."departments" to "service_role";

grant select on table "public"."departments" to "service_role";

grant trigger on table "public"."departments" to "service_role";

grant truncate on table "public"."departments" to "service_role";

grant update on table "public"."departments" to "service_role";

grant delete on table "public"."faculties" to "anon";

grant insert on table "public"."faculties" to "anon";

grant references on table "public"."faculties" to "anon";

grant select on table "public"."faculties" to "anon";

grant trigger on table "public"."faculties" to "anon";

grant truncate on table "public"."faculties" to "anon";

grant update on table "public"."faculties" to "anon";

grant delete on table "public"."faculties" to "authenticated";

grant insert on table "public"."faculties" to "authenticated";

grant references on table "public"."faculties" to "authenticated";

grant select on table "public"."faculties" to "authenticated";

grant trigger on table "public"."faculties" to "authenticated";

grant truncate on table "public"."faculties" to "authenticated";

grant update on table "public"."faculties" to "authenticated";

grant delete on table "public"."faculties" to "postgres";

grant insert on table "public"."faculties" to "postgres";

grant references on table "public"."faculties" to "postgres";

grant select on table "public"."faculties" to "postgres";

grant trigger on table "public"."faculties" to "postgres";

grant truncate on table "public"."faculties" to "postgres";

grant update on table "public"."faculties" to "postgres";

grant delete on table "public"."faculties" to "service_role";

grant insert on table "public"."faculties" to "service_role";

grant references on table "public"."faculties" to "service_role";

grant select on table "public"."faculties" to "service_role";

grant trigger on table "public"."faculties" to "service_role";

grant truncate on table "public"."faculties" to "service_role";

grant update on table "public"."faculties" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."programs" to "anon";

grant insert on table "public"."programs" to "anon";

grant references on table "public"."programs" to "anon";

grant select on table "public"."programs" to "anon";

grant trigger on table "public"."programs" to "anon";

grant truncate on table "public"."programs" to "anon";

grant update on table "public"."programs" to "anon";

grant delete on table "public"."programs" to "authenticated";

grant insert on table "public"."programs" to "authenticated";

grant references on table "public"."programs" to "authenticated";

grant select on table "public"."programs" to "authenticated";

grant trigger on table "public"."programs" to "authenticated";

grant truncate on table "public"."programs" to "authenticated";

grant update on table "public"."programs" to "authenticated";

grant delete on table "public"."programs" to "postgres";

grant insert on table "public"."programs" to "postgres";

grant references on table "public"."programs" to "postgres";

grant select on table "public"."programs" to "postgres";

grant trigger on table "public"."programs" to "postgres";

grant truncate on table "public"."programs" to "postgres";

grant update on table "public"."programs" to "postgres";

grant delete on table "public"."programs" to "service_role";

grant insert on table "public"."programs" to "service_role";

grant references on table "public"."programs" to "service_role";

grant select on table "public"."programs" to "service_role";

grant trigger on table "public"."programs" to "service_role";

grant truncate on table "public"."programs" to "service_role";

grant update on table "public"."programs" to "service_role";


  create policy "Select departments (authenticated)"
  on "public"."departments"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Select faculties (authenticated)"
  on "public"."faculties"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Insert own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((id = auth.uid()));



  create policy "Select own profile"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((id = auth.uid()));



  create policy "Update own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((id = auth.uid()))
with check ((id = auth.uid()));



  create policy "Enable read access for all auth users"
  on "public"."programs"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER set_departments_updated_at BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION public.set_timestamp_updated_at();

CREATE TRIGGER set_faculties_updated_at BEFORE UPDATE ON public.faculties FOR EACH ROW EXECUTE FUNCTION public.set_timestamp_updated_at();

CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_timestamp_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();



